services:
  app:
    build: .
    logging:
      driver: local
    tty: true
    volumes:
      - proxy_spider_cache:/home/app/.cache/proxy_spider
      - ./out:/home/app/.local/share/proxy_spider
      - ./config.toml:/app/config.toml
volumes:
  proxy_spider_cache:
