name: Update dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: "30 1 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update-dependencies:
    if: ${{ github.repository_owner == 'threatcode' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - cmd: uv dep update --all
            commit-msg: Update dependencies
            branch: update/dependencies
          - cmd: pipx run pre-commit autoupdate
            commit-msg: Update .pre-commit-config.yaml
            branch: update/pre-commit-config
      fail-fast: false

    steps:
      - uses: actions/checkout@v5

      - run: ${{ matrix.cmd }}
        shell: bash

      - uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: ${{ matrix.commit-msg }}
          author: github-actions[bot] <120432727+github-actions[bot]@users.noreply.github.com>
          branch: ${{ matrix.branch }}
          delete-branch: true
          title: ${{ matrix.commit-msg }}
          body: |
            This pull request updates the following:
            - Project dependencies using `uv`
            - Pre-commit configuration
